name: Style

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  check_style:
    name: "Check style"
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1

    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r test-requirements.txt
    - name: "run black"
      run: |
          black --check --config .black.toml .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 shmutils/ tests/ examples/ setup.py  --count --select=E9,F63,F7,F82 --show-source --statistics
